version: '3.8'

services:
  db:
    image: postgres
    environment:
        POSTGRES_DB: crypto_db
        POSTGRES_USER: admin 
        POSTGRES_PASSWORD: adminpassword

    ports:
      - "5432:5432"
 